spring.data.mongodb.uri=mongodb://127.0.0.1:27017/CloudShare

server.servlet.context-path=/api/v1.0
server.port=9090

#spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://live-duckling-54.clerk.accounts.dev
clerk.jwks-url=https://live-duckling-54.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_tAl0xR/A/pmGplGeqqBq0pmIUkzGG0uC

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay configuration
razorpay.key.id=rzp_test_SJT9lYZL3JHDQH
razorpay.key.secret=rhhL6raZ3bIRBfvQxra6IrDh